// <auto-generated />
using System;
using IchigoHoshimiya.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IchigoHoshimiya.Migrations
{
    [DbContext(typeof(IchigoContext))]
    [Migration("20250831160917_AddAnilistIdToAiringAnime")]
    partial class AddAnilistIdToAiringAnime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IchigoHoshimiya.Entities.AniList.AiringAnime", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("AnilistId")
                        .HasColumnType("bigint")
                        .HasColumnName("anilist_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("anime_title");

                    b.HasKey("Id");

                    b.ToTable("AiringAnime");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.AniList.AiringEpisodes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("AiringAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("airing_at_utc");

                    b.Property<long>("AnimeId")
                        .HasColumnType("bigint")
                        .HasColumnName("anime_id");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("int")
                        .HasColumnName("episode_number");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.ToTable("AiringEpisodes");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.AniList.AiringEpisodes", b =>
                {
                    b.HasOne("IchigoHoshimiya.Entities.AniList.AiringAnime", "Anime")
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });
#pragma warning restore 612, 618
        }
    }
}
