// <auto-generated />
using System;
using IchigoHoshimiya.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IchigoHoshimiya.Migrations
{
    [DbContext(typeof(IchigoContext))]
    [Migration("20250904210407_AddRssReminderTable")]
    partial class AddRssReminderTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IchigoHoshimiya.Entities.AniList.AiringAnime", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("AnilistId")
                        .HasColumnType("bigint")
                        .HasColumnName("anilist_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("varchar(10000)")
                        .HasColumnName("anime_title");

                    b.HasKey("Id");

                    b.ToTable("airing_anime");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.AniList.AiringEpisode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("AiringAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("airing_at_utc");

                    b.Property<long>("AnimeId")
                        .HasColumnType("bigint")
                        .HasColumnName("anime_id");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("int")
                        .HasColumnName("episode_number");

                    b.HasKey("Id");

                    b.HasIndex("AiringAtUtc");

                    b.HasIndex("AnimeId");

                    b.ToTable("airing_episode");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.General.RssReminder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<string>("Mentions")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mentions");

                    b.Property<string>("SearchString")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("search_string");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("CreatedById");

                    b.ToTable("rss_reminder");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.AniList.AiringEpisode", b =>
                {
                    b.HasOne("IchigoHoshimiya.Entities.AniList.AiringAnime", "Anime")
                        .WithMany("AiringEpisodes")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.AniList.AiringAnime", b =>
                {
                    b.Navigation("AiringEpisodes");
                });
#pragma warning restore 612, 618
        }
    }
}
